# Generated by Django 6.0.1 on 2026-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
