# Generated by Django 6.0.1 on 2026-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='leave_balance',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_unit',
            field=models.CharField(blank=True, choices=[('Aerospace Department', 'Aerospace Department'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='discipline',
            field=models.CharField(blank=True, choices=[('Aerospace Engineering', 'Aerospace Engineering'), ('Other', 'Other')], max_length=100),
        ),
    ]
