# Generated by Django 6.0.1 on 2026-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leaveapplication_status_student_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_leaves',
            field=models.IntegerField(default=15),
        ),
    ]
