# Generated by Django 6.0.1 on 2026-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_total_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('TA', 'TA'), ('TAP', 'TAP'), ('RA', 'RA'), ('FA', 'FA')], max_length=3, verbose_name='Category of Registration'),
        ),
    ]
