# Generated by Django 6.0.1 on 2026-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='place_of_visit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
