# Generated by Django 6.0.1 on 2026-04-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_leavetype_is_periodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='faculty_advisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='thesis_supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
