# Generated by Django 6.0.2 on 2026-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_leaveapplication_faculty_advisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='stipend_status',
            field=models.CharField(blank=True, choices=[('continue', 'My stipend/scholarship from the Institute should be continued during the leave period.'), ('not_continue', 'My stipend/scholarship from the Institute need not be continued during the leave period.'), ('not_supported', 'I am not supported by a stipend/scholarship from the Institute.')], max_length=20),
        ),
    ]
