# Generated by Django 6.0.1 on 2026-04-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_leaveapplication_stipend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='rejection_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rejection_pdfs/'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
