# Generated by Django 6.0.1 on 2026-04-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_leaveapplication_rejection_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
