# Generated by Django 6.0.1 on 2026-04-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_leaveapplication_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
