# Generated by Django 6.0.1 on 2026-04-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_leaveapplication_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_students_tab', models.BooleanField(default=False, verbose_name='Show Students tab')),
                ('show_policies_tab', models.BooleanField(default=False, verbose_name='Show Policies tab')),
                ('show_status_cards', models.BooleanField(default=True, verbose_name='Show status summary cards')),
                ('show_app_no', models.BooleanField(default=True, verbose_name='App No')),
                ('show_student_name', models.BooleanField(default=True, verbose_name='Student Name')),
                ('show_roll', models.BooleanField(default=True, verbose_name='Roll Number')),
                ('show_type', models.BooleanField(default=True, verbose_name='Leave Type')),
                ('show_period', models.BooleanField(default=True, verbose_name='Period')),
                ('show_days', models.BooleanField(default=True, verbose_name='Days')),
                ('show_leaves_taken', models.BooleanField(default=True, verbose_name='Leaves Taken')),
                ('show_purpose', models.BooleanField(default=True, verbose_name='Purpose')),
                ('show_status', models.BooleanField(default=True, verbose_name='Status')),
                ('show_submitted', models.BooleanField(default=True, verbose_name='Submitted Date')),
                ('can_approve', models.BooleanField(default=True, verbose_name='Can approve applications')),
                ('can_reject', models.BooleanField(default=True, verbose_name='Can reject applications')),
                ('show_stu_name', models.BooleanField(default=True, verbose_name='Student Name')),
                ('show_stu_roll', models.BooleanField(default=True, verbose_name='Roll Number')),
                ('show_stu_gender', models.BooleanField(default=True, verbose_name='Gender')),
                ('show_stu_programme', models.BooleanField(default=True, verbose_name='Programme')),
                ('show_stu_discipline', models.BooleanField(default=True, verbose_name='Discipline')),
                ('show_stu_specialization', models.BooleanField(default=True, verbose_name='Specialization')),
                ('show_stu_taken', models.BooleanField(default=True, verbose_name='Leaves Taken')),
            ],
            options={
                'verbose_name': 'Approver Configuration',
                'verbose_name_plural': 'Approver Configuration',
            },
        ),
    ]
