# Generated by Django 6.0.1 on 2026-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_approverconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=False, verbose_name='Enable auto-backup')),
                ('backup_interval_days', models.IntegerField(default=7, verbose_name='Backup interval (days)')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='Last backup time')),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configuration',
            },
        ),
    ]
