# Generated by Django 6.0.1 on 2026-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_backupconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Auto-Backup'),
        ),
        migrations.AlterField(
            model_name='backupconfig',
            name='backup_interval_days',
            field=models.IntegerField(default=7, verbose_name='Backup Interval (Days)'),
        ),
        migrations.AlterField(
            model_name='backupconfig',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Backup Performed At'),
        ),
    ]
