# Generated by Django 6.0.1 on 2026-04-29 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_backupconfig_auto_backup_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeaveAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_days', models.IntegerField(default=0, help_text='Add or subtract days from the "taken" count')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leavetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'leave_type')},
            },
        ),
    ]
