# Generated by Django 6.0.2 on 2026-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_populate_new_leave_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverconfig',
            name='current_academic_year',
            field=models.IntegerField(default=2025, verbose_name='Current Academic Year'),
        ),
    ]
